import { Client, Invoice, Expense, Employee } from "@shared/schema";

export const mockClients: Client[] = [
  {
    id: "1",
    userId: "user1",
    name: "TechStart Inc.",
    businessType: "LLC",
    taxId: "12-3456789",
    industry: "Technology",
    address: "123 Tech Ave, San Francisco, CA 94105",
    email: "contact@techstart.com",
    phone: "+1 (555) 123-4567",
    status: "active",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    userId: "user1",
    name: "Downtown Cafe",
    businessType: "Sole Proprietorship",
    taxId: "98-7654321",
    industry: "Restaurant",
    address: "456 Main St, Portland, OR 97201",
    email: "info@downtowncafe.com",
    phone: "+1 (555) 987-6543",
    status: "active",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    userId: "user1",
    name: "Green Energy Co.",
    businessType: "Corporation",
    taxId: "55-1234567",
    industry: "Energy",
    address: "789 Solar Blvd, Austin, TX 78701",
    email: "hello@greenenergy.com",
    phone: "+1 (555) 456-7890",
    status: "active",
    createdAt: new Date("2024-01-30"),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    clientId: "1",
    invoiceNumber: "INV-1024",
    description: "Web Development Services - December 2024",
    amount: "3200.00",
    status: "overdue",
    issueDate: new Date("2024-12-01"),
    dueDate: new Date("2024-12-15"),
    paidDate: null,
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "inv2",
    clientId: "2",
    invoiceNumber: "INV-1025",
    description: "Monthly Accounting Services",
    amount: "1500.00",
    status: "paid",
    issueDate: new Date("2024-12-01"),
    dueDate: new Date("2024-12-31"),
    paidDate: new Date("2024-12-20"),
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "inv3",
    clientId: "3",
    invoiceNumber: "INV-1026",
    description: "Financial Consulting Q4",
    amount: "5600.00",
    status: "sent",
    issueDate: new Date("2024-12-15"),
    dueDate: new Date("2025-01-15"),
    paidDate: null,
    createdAt: new Date("2024-12-15"),
  },
];

export const mockExpenses: Expense[] = [
  {
    id: "exp1",
    clientId: "1",
    description: "Office Supplies - Staples",
    category: "Office Supplies",
    amount: "156.78",
    date: new Date("2024-12-10"),
    receiptUrl: "/receipts/staples-receipt.pdf",
    status: "flagged",
    aiCategorized: true,
    createdAt: new Date("2024-12-10"),
  },
  {
    id: "exp2",
    clientId: "2",
    description: "Business Lunch - Client Meeting",
    category: "Meals & Entertainment",
    amount: "89.50",
    date: new Date("2024-12-08"),
    receiptUrl: "/receipts/restaurant-receipt.jpg",
    status: "approved",
    aiCategorized: true,
    createdAt: new Date("2024-12-08"),
  },
  {
    id: "exp3",
    clientId: "1",
    description: "Software License - Adobe Creative Suite",
    category: "Software",
    amount: "299.99",
    date: new Date("2024-12-05"),
    receiptUrl: "/receipts/adobe-invoice.pdf",
    status: "approved",
    aiCategorized: true,
    createdAt: new Date("2024-12-05"),
  },
];

export const mockEmployees: Employee[] = [
  {
    id: "emp1",
    clientId: "1",
    firstName: "John",
    lastName: "Smith",
    email: "john@techstart.com",
    role: "Senior Developer",
    salary: "95000.00",
    status: "active",
    hireDate: new Date("2023-03-15"),
    createdAt: new Date("2023-03-15"),
  },
  {
    id: "emp2",
    clientId: "1",
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah@techstart.com",
    role: "Product Manager",
    salary: "85000.00",
    status: "active",
    hireDate: new Date("2023-06-01"),
    createdAt: new Date("2023-06-01"),
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "overdue",
    message: "Invoice #1024 is 5 days overdue",
    client: "TechStart Inc.",
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: "2",
    type: "expense",
    message: "New expense report uploaded for review",
    client: "Downtown Cafe",
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
  },
  {
    id: "3",
    type: "payroll",
    message: "Payroll processed successfully",
    client: "TechStart Inc.",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
];

export const mockCashFlowData = {
  labels: ["Aug", "Sep", "Oct", "Nov", "Dec", "Jan"],
  datasets: [
    {
      label: "Income",
      data: [45000, 52000, 48000, 58000, 65000, 72000],
      borderColor: "hsl(142, 71%, 45%)",
      backgroundColor: "hsla(142, 71%, 45%, 0.1)",
      tension: 0.4,
    },
    {
      label: "Expenses",
      data: [32000, 35000, 31000, 38000, 42000, 45000],
      borderColor: "hsl(0, 84%, 60%)",
      backgroundColor: "hsla(0, 84%, 60%, 0.1)",
      tension: 0.4,
    },
  ],
};

export const mockAIInsights = [
  {
    id: "1",
    type: "cash_flow",
    title: "Cash Flow Alert",
    description: "TechStart Inc payment is 5 days overdue - affecting working capital",
    severity: "high",
    actionable: true,
  },
  {
    id: "2",
    type: "tax_optimization",
    title: "Tax Deduction Opportunity",
    description: "Found $2,400 in eligible home office deductions for Q4",
    severity: "medium",
    actionable: true,
  },
  {
    id: "3",
    type: "expense_pattern",
    title: "Unusual Expense Pattern",
    description: "Office supplies spending increased 40% this month",
    severity: "low",
    actionable: false,
  },
];
